"""A-CASE Phase 7: the validation ladder runner and its summarizer.

A smoke test on the two rungs that need no optional extras -- a TFIM chain and a
Hubbard cluster -- covering every method kind the ladder can run, including the
finite-shot ones at a token budget. The committed record is generated by the
same code path on the full ladder; what is checked here is that each method
produces a row with the fields §7 asks for, that the labels stay honest, and
that the summarizer regenerates deterministically (which is what
``check_summaries.py`` enforces for the committed companions).
"""

import json
import sys
from pathlib import Path

import pytest

BENCH = Path(__file__).resolve().parent.parent / "benchmarks"
sys.path.insert(0, str(BENCH))
try:
    import run_acase_ladder  # noqa: E402
    import summarize_ladder  # noqa: E402
finally:
    sys.path.remove(str(BENCH))

TINY_CONFIG = {
    "methods": {
        "exact": {"kind": "exact", "family": "reference"},
        "reference_state": {"kind": "reference_state", "family": "reference"},
        "qse": {"kind": "qse", "size": 4, "family": "fixed"},
        "krylov": {"kind": "krylov", "size": 3, "family": "fixed"},
        "generator_coordinate": {"kind": "generator_coordinate", "size": 4,
                                 "family": "fixed"},
        "adapt_exact": {"kind": "adapt_exact", "max_operators": 2, "family": "adapt"},
        "adapt_shot": {"kind": "adapt_shot", "max_operators": 1, "base": 64,
                       "max_factor": 4, "near_tol": 0.2, "family": "adapt"},
        "acase_exact": {"kind": "acase_exact", "max_size": 3, "family": "acase"},
        "acase_states": {"kind": "acase_exact", "max_size": 3, "roots": 2,
                         "family": "acase"},
        "acase_certified": {"kind": "acase_certified", "max_size": 1,
                            "construction_shots": 200, "certification_shots": 200,
                            "threshold": 0.05, "family": "acase"},
    },
    "ladder": [
        {"name": "tfim4", "rung": 1, "system": {"type": "tfim", "n": 4},
         "krylov_order": 3,
         "methods": ["exact", "reference_state", "qse", "krylov", "adapt_exact",
                     "adapt_shot", "acase_exact", "acase_certified"]},
        {"name": "hubbard_1x2", "rung": 2,
         "system": {"type": "hubbard", "shape": 2},
         "methods": ["exact", "reference_state", "generator_coordinate",
                     "acase_exact", "acase_states"]},
    ],
}


@pytest.fixture(scope="module")
def ladder(tmp_path_factory):
    pytest.importorskip("scipy")
    directory = tmp_path_factory.mktemp("ladder")
    config = directory / "config.json"
    config.write_text(json.dumps(TINY_CONFIG))
    out = directory / "ladder.jsonl"
    run_acase_ladder.main(["--config", str(config), "--out", str(out)])
    rows = [json.loads(line) for line in out.read_text().splitlines()]
    return directory, out, rows


def test_every_method_produces_a_row_with_the_required_fields(ladder):
    _, _, rows = ladder
    assert len(rows) == 8 + 5
    for row in rows:
        assert {"system", "rung", "rung_name", "n", "method", "family", "evidence",
                "energy", "reference_energy", "error", "relative_error",
                "chemical_accuracy", "hamiltonian_terms", "candidate_pool",
                "word_pool", "wall_seconds"} <= set(row)
        assert row["error"] == pytest.approx(row["energy"] - row["reference_energy"])


def test_the_exact_row_is_the_reference_every_error_is_measured_against(ladder):
    _, _, rows = ladder
    for name in ("tfim4", "hubbard_1x2"):
        exact = next(r for r in rows if r["rung_name"] == name and r["method"] == "exact")
        assert exact["evidence"] == "reference"
        assert exact["error"] == pytest.approx(0.0, abs=1e-12)
        others = [r for r in rows if r["rung_name"] == name and r["method"] != "exact"]
        # every exact-arithmetic subspace row obeys the variational bound
        for row in others:
            if row["evidence"] == "exact":
                assert row["energy"] >= exact["energy"] - 1e-8


def test_resource_columns_accompany_the_subspace_rows(ladder):
    """§7: energies *and* the §6 metrics, not energies alone."""
    _, _, rows = ladder
    for row in rows:
        if row["method"] in ("qse", "krylov", "generator_coordinate", "acase_exact",
                             "acase_states"):
            assert row["basis_size"] >= 1
            assert row["retained_rank"] >= 1
            assert row["condition_number"] >= 1.0 - 1e-9
            if row.get("support_tracked", True):
                assert row["word_universe"] >= 1
                assert row["max_element_support"] >= 1


def test_finite_shot_rows_carry_shots_circuits_and_abstentions(ladder):
    _, _, rows = ladder
    for method in ("adapt_shot", "acase_certified"):
        row = next(r for r in rows if r["method"] == method)
        assert row["evidence"] == "finite_sample"
        assert row["total_shots"] > 0
        assert row["total_circuits"] > 0
        assert row["abstentions"] >= 0
    for method in ("exact", "acase_exact", "qse"):
        row = next(r for r in rows if r["method"] == method)
        assert row.get("total_shots", 0) == 0


def test_lattice_rungs_report_projected_observables(ladder):
    """The Hubbard rung's observables come through the §8 route for A-CASE rows
    and from the exact state for the reference row."""
    _, _, rows = ladder
    hubbard_rows = [r for r in rows if r["rung_name"] == "hubbard_1x2"]
    exact = next(r for r in hubbard_rows if r["method"] == "exact")
    acase = next(r for r in hubbard_rows if r["method"] == "acase_exact")
    assert set(exact["observables"]) == {"double_occupancy", "spin_correlation_01",
                                         "structure_factor", "total_spin_squared"}
    assert set(acase["observables"]) == set(exact["observables"])
    # the two-site cluster is reached exactly, so the observables must agree
    assert acase["energy"] == pytest.approx(exact["energy"], abs=1e-8)
    for name, value in exact["observables"].items():
        assert acase["observables"][name] == pytest.approx(value, abs=1e-6)


def test_multi_root_row_reports_its_roots(ladder):
    _, _, rows = ladder
    row = next(r for r in rows if r["method"] == "acase_states")
    assert len(row["root_energies"]) == 2
    assert row["energy"] == pytest.approx(sum(row["root_energies"]) / 2, abs=1e-9)


def test_summarizer_is_deterministic_and_reports_the_evidence(ladder):
    directory, out, rows = ladder
    csv_path = directory / "summary.csv"
    first = summarize_ladder.markdown(rows)
    summarize_ladder.write_csv(rows, csv_path)
    assert summarize_ladder.markdown(rows) == first  # byte-identical regeneration
    assert "evidence" in first and "finite_sample" in first
    assert "Reached chemical accuracy" in first
    assert "no variational guarantee" in first  # the Q3 caveat is not silent
    # the reference determinant gets its own column rather than competing for
    # "most compact subspace" on rungs where HF is already accurate
    assert "| rung | reference determinant |" in first
    assert "reference_state" not in first.split("Reached chemical accuracy")[1]
    header = csv_path.read_text().splitlines()[0]
    assert header.startswith("rung,system,n,method,evidence,energy,error")
    assert len(csv_path.read_text().splitlines()) == len(rows) + 1


def test_untracked_support_is_not_rendered_as_inapplicable():
    """"-" means the column does not apply; a deliberate cyclic-route fallback
    is a different statement and gets its own marker."""
    absent = {"method": "reference_state"}
    fallback = {"method": "krylov", "support_tracked": False}
    tracked = {"method": "krylov", "support_tracked": True, "word_universe": 12}
    assert summarize_ladder.cell(absent, "word_universe") == "-"
    assert summarize_ladder.cell(fallback, "word_universe") == "n/t"
    assert summarize_ladder.cell(fallback, "max_element_support") == "n/t"
    assert summarize_ladder.cell(fallback, "basis_size") == "-"  # still just absent
    assert summarize_ladder.cell(tracked, "word_universe") == "12"


def test_summarizer_rejects_a_foreign_schema(tmp_path):
    record = tmp_path / "foreign.jsonl"
    record.write_text(json.dumps({"model": "tfim", "method": "exact"}) + "\n")
    with pytest.raises(SystemExit, match="not an A-CASE ladder record"):
        summarize_ladder.load(record)


def test_generator_coordinate_selection_spans_the_candidate_family():
    """A fixed subspace is chosen before any measurement, so *which* fixed slice
    is part of the method. The committed record uses ``stride`` because the
    natural prefix of an excitation family is all singles -- Brillouin-dead on a
    Hartree-Fock reference -- and would report the reference energy as a subspace
    result. Both slices stay available and the row records which one it used.
    """
    from clifford_qc.backends import ExactMVBackend

    model, kind = run_acase_ladder.build_system({"type": "tfim", "n": 4})
    context = {"rho": ExactMVBackend().state(model.reference, ()), "observables": {},
               "candidates": run_acase_ladder.build_candidates(model, kind, 3),
               "pool": run_acase_ladder.word_pool(model, kind)}
    spec = {"kind": "generator_coordinate", "size": 4}
    prefix = run_acase_ladder.run_method("gc", spec | {"selection": "prefix"},
                                         model, kind, context)
    stride = run_acase_ladder.run_method("gc", spec | {"selection": "stride"},
                                         model, kind, context)
    assert prefix["selection"] == "prefix" and stride["selection"] == "stride"
    assert prefix["labels"] != stride["labels"]
    assert run_acase_ladder.run_method("gc", spec, model, kind,
                                       context)["labels"] == stride["labels"]
    # the strided slice reaches deeper into the family than the prefix does
    order = [candidate.label for candidate in context["candidates"]]
    assert order.index(stride["labels"][-1]) > order.index(prefix["labels"][-1])
    with pytest.raises(ValueError, match="unknown generator-coordinate selection"):
        run_acase_ladder.run_method("gc", spec | {"selection": "middle"},
                                    model, kind, context)


def test_unknown_systems_and_methods_are_rejected():
    with pytest.raises(ValueError, match="unknown system type"):
        run_acase_ladder.build_system({"type": "graphene"})
    model, kind = run_acase_ladder.build_system({"type": "tfim", "n": 3})
    with pytest.raises(ValueError, match="unknown method kind"):
        run_acase_ladder.run_method("x", {"kind": "telepathy"}, model, kind, {})
