"""A-CASE Phase 7: the validation ladder runner and its summarizer.

A smoke test on the two rungs that need no optional extras -- a TFIM chain and a
Hubbard cluster -- covering every method kind the ladder can run, including the
finite-shot ones at a token budget. The committed record is generated by the
same code path on the full ladder; what is checked here is that each method
produces a row with the fields §7 asks for, that the labels stay honest, and
that the summarizer regenerates deterministically (which is what
``check_summaries.py`` enforces for the committed companions).
"""

import json
import sys
from pathlib import Path

import pytest

BENCH = Path(__file__).resolve().parent.parent / "benchmarks"
sys.path.insert(0, str(BENCH))
try:
    import run_acase_ladder  # noqa: E402
    import summarize_ladder  # noqa: E402
finally:
    sys.path.remove(str(BENCH))

TINY_CONFIG = {
    "methods": {
        "exact": {"kind": "exact", "family": "reference"},
        "reference_state": {"kind": "reference_state", "family": "reference"},
        "qse": {"kind": "qse", "size": 4, "family": "fixed"},
        "krylov": {"kind": "krylov", "size": 3, "family": "fixed"},
        "generator_coordinate": {"kind": "generator_coordinate", "size": 4,
                                 "family": "fixed"},
        "adapt_exact": {"kind": "adapt_exact", "max_operators": 2, "family": "adapt"},
        "adapt_shot": {"kind": "adapt_shot", "max_operators": 1, "base": 64,
                       "max_factor": 4, "near_tol": 0.2, "family": "adapt"},
        "acase_exact": {"kind": "acase_exact", "max_size": 3, "family": "acase"},
        "acase_states": {"kind": "acase_exact", "max_size": 3, "roots": 2,
                         "family": "acase"},
        "acase_certified": {"kind": "acase_certified", "max_size": 1,
                            "construction_shots": 200, "certification_shots": 200,
                            "threshold": 0.05, "family": "acase"},
        "qsci_reference": {"kind": "qsci", "input": "reference", "shots": 64,
                           "family": "qsci"},
    },
    "ladder": [
        {"name": "tfim4", "rung": 1, "system": {"type": "tfim", "n": 4},
         "krylov_order": 3,
         "methods": ["exact", "reference_state", "qse", "krylov", "adapt_exact",
                     "adapt_shot", "acase_exact", "acase_certified"]},
        {"name": "hubbard_1x2", "rung": 2,
         "system": {"type": "hubbard", "shape": 2},
         "methods": ["exact", "reference_state", "generator_coordinate",
                     "acase_exact", "acase_states", "qsci_reference"]},
    ],
}


@pytest.fixture(scope="module")
def ladder(tmp_path_factory):
    pytest.importorskip("scipy")
    directory = tmp_path_factory.mktemp("ladder")
    config = directory / "config.json"
    config.write_text(json.dumps(TINY_CONFIG))
    out = directory / "ladder.jsonl"
    run_acase_ladder.main(["--config", str(config), "--out", str(out)])
    rows = [json.loads(line) for line in out.read_text().splitlines()]
    return directory, out, rows


def test_every_method_produces_a_row_with_the_required_fields(ladder):
    _, _, rows = ladder
    assert len(rows) == 9 + 5
    for row in rows:
        assert {"system", "rung", "rung_name", "n", "method", "family", "evidence",
                "energy", "reference_energy", "error", "relative_error",
                "chemical_accuracy", "hamiltonian_terms", "candidate_pool",
                "word_pool", "wall_seconds"} <= set(row)
        assert row["error"] == pytest.approx(row["energy"] - row["reference_energy"])


def test_the_exact_row_is_the_reference_every_error_is_measured_against(ladder):
    _, _, rows = ladder
    for name in ("tfim4", "hubbard_1x2"):
        exact = next(r for r in rows if r["rung_name"] == name and r["method"] == "exact")
        assert exact["evidence"] == "reference"
        assert exact["error"] == pytest.approx(0.0, abs=1e-12)
        others = [r for r in rows if r["rung_name"] == name and r["method"] != "exact"]
        # every exact-arithmetic subspace row obeys the variational bound
        for row in others:
            if row["evidence"] == "exact":
                assert row["energy"] >= exact["energy"] - 1e-8


def test_resource_columns_accompany_the_subspace_rows(ladder):
    """§7: energies *and* the §6 metrics, not energies alone."""
    _, _, rows = ladder
    for row in rows:
        if row["method"] in ("qse", "krylov", "generator_coordinate", "acase_exact",
                             "acase_states"):
            assert row["basis_size"] >= 1
            assert row["retained_rank"] >= 1
            assert row["condition_number"] >= 1.0 - 1e-9
            if row.get("support_tracked", True):
                assert row["word_universe"] >= 1
                assert row["max_element_support"] >= 1


def test_finite_shot_rows_carry_shots_circuits_and_abstentions(ladder):
    _, _, rows = ladder
    for method in ("adapt_shot", "acase_certified"):
        row = next(r for r in rows if r["method"] == method)
        assert row["evidence"] == "finite_sample"
        assert row["total_shots"] > 0
        assert row["total_circuits"] > 0
        assert row["abstentions"] >= 0
    for method in ("exact", "acase_exact", "qse"):
        row = next(r for r in rows if r["method"] == method)
        assert row.get("total_shots", 0) == 0

    qsci = next(r for r in rows if r["method"] == "qsci_reference")
    assert qsci["evidence"] == "finite_sample"
    assert qsci["sampling_source"] == "exact_probabilities"
    assert qsci["raw_shots"] == 64
    assert qsci["state_preparations"] == 1
    assert qsci["state_preparation_executions"] == 64
    assert qsci["peak_rss_bytes"] is None or qsci["peak_rss_bytes"] > 0


def test_lattice_rungs_report_projected_observables(ladder):
    """The Hubbard rung's observables come through the §8 route for A-CASE rows
    and from the exact state for the reference row."""
    _, _, rows = ladder
    hubbard_rows = [r for r in rows if r["rung_name"] == "hubbard_1x2"]
    exact = next(r for r in hubbard_rows if r["method"] == "exact")
    acase = next(r for r in hubbard_rows if r["method"] == "acase_exact")
    assert set(exact["observables"]) == {"double_occupancy", "spin_correlation_01",
                                         "structure_factor", "total_spin_squared"}
    assert set(acase["observables"]) == set(exact["observables"])
    # the two-site cluster is reached exactly, so the observables must agree
    assert acase["energy"] == pytest.approx(exact["energy"], abs=1e-8)
    for name, value in exact["observables"].items():
        assert acase["observables"][name] == pytest.approx(value, abs=1e-6)


def test_multi_root_row_reports_its_roots(ladder):
    _, _, rows = ladder
    row = next(r for r in rows if r["method"] == "acase_states")
    assert len(row["root_energies"]) == 2
    assert row["energy"] == pytest.approx(sum(row["root_energies"]) / 2, abs=1e-9)


def test_summarizer_is_deterministic_and_reports_the_evidence(ladder):
    directory, out, rows = ladder
    csv_path = directory / "summary.csv"
    first = summarize_ladder.markdown(rows)
    summarize_ladder.write_csv(rows, csv_path)
    assert summarize_ladder.markdown(rows) == first  # byte-identical regeneration
    assert "evidence" in first and "finite_sample" in first
    assert "Reached chemical accuracy" in first
    assert "no variational guarantee" in first  # the Q3 caveat is not silent
    # the reference determinant gets its own column rather than competing for
    # "most compact subspace" on rungs where HF is already accurate
    assert "| rung | reference determinant |" in first
    assert "reference_state" not in first.split("Reached chemical accuracy")[1]
    header = csv_path.read_text().splitlines()[0]
    assert header.startswith("rung,system,n,method,evidence,energy,error")
    assert len(csv_path.read_text().splitlines()) == len(rows) + 1


def test_oracle_and_reference_qsci_cannot_enter_competitive_summary():
    """Validation/control rows stay visible without becoming method claims."""
    base = {"system": "toy", "rung": 1, "rung_name": "toy", "n": 2,
            "energy": -1.0, "reference_energy": -1.0, "error": 0.0,
            "chemical_accuracy": True, "basis_size": 1, "family": "qsci",
            "evidence": "finite_sample"}
    rows = [
        base | {"method": "reference_state", "family": "reference",
                "evidence": "exact"},
        base | {"method": "qsci_reference", "input_category": "implementable",
                "sampling_state": "reference_determinant"},
        base | {"method": "qsci_oracle", "input_category": "oracle",
                "sampling_state": "exact_ground_oracle"},
        base | {"method": "real_method", "family": "fixed", "evidence": "exact",
                "basis_size": 3},
    ]
    report = summarize_ladder.markdown(rows)
    claim = report.split("### Reached chemical accuracy", 1)[1].split(
        "### Sampled subspaces", 1)[0]
    assert "real_method" in claim
    assert "qsci_reference" not in claim
    assert "qsci_oracle" not in claim
    assert "most compact exact-arithmetic" in claim


def test_the_fermionic_leakage_filter_is_not_applied_to_a_spin_model():
    """A global method spec carries one ``leakage_tol`` for every rung, and
    ``sector_leakage`` measures the *fermionic* symmetries. On a spin lattice
    there is no particle number to conserve, every candidate leaks, and the
    filter rejects the whole pool -- which reads as A-CASE failing to grow when
    it is the configuration that is wrong. The tolerance is dropped there, and
    the row says so rather than staying silent.
    """
    spec = {"leakage_tol": 1e-9}
    assert run_acase_ladder.leakage_tolerance(dict(spec), "molecular") \
        == (1e-9, "applied at 1e-09")
    assert run_acase_ladder.leakage_tolerance(dict(spec), "fermionic_lattice")[0] == 1e-9
    tol, note = run_acase_ladder.leakage_tolerance(dict(spec), "spin_lattice")
    assert tol is None and "no fermionic sector" in note
    assert run_acase_ladder.leakage_tolerance({}, "spin_lattice") == (None,
                                                                     "not requested")


def test_a_spin_lattice_rung_still_grows_under_a_requested_leakage_tolerance():
    """The regression the guard exists for, end to end: with the filter wrongly
    applied the Kitaev cluster stalls at the reference energy with a basis of
    one; with the guard it reaches the cluster's exact ground state."""
    pytest.importorskip("scipy")
    from clifford_qc.backends import ExactMVBackend

    model = run_acase_ladder.build_system({"type": "kitaev", "rows": 2, "cols": 2})
    reference, _ = run_acase_ladder.reference_energy(model)
    context = {"rho": ExactMVBackend().state(model.reference, ()), "observables": {},
               "reference": reference,
               "candidates": run_acase_ladder.build_candidates(model, 8),
               "pool": run_acase_ladder.word_pool(model)}
    row = run_acase_ladder.run_method(
        "acase_exact", {"kind": "acase_exact", "max_size": 8, "leakage_tol": 1e-9},
        model, context)
    assert "no fermionic sector" in row["leakage_filter"]
    assert row["energy"] == pytest.approx(reference, abs=1e-8)
    assert row["basis_size"] > 1


def test_untracked_support_is_not_rendered_as_inapplicable():
    """"-" means the column does not apply; a deliberate cyclic-route fallback
    is a different statement and gets its own marker."""
    absent = {"method": "reference_state"}
    fallback = {"method": "krylov", "support_tracked": False}
    tracked = {"method": "krylov", "support_tracked": True, "word_universe": 12}
    assert summarize_ladder.cell(absent, "word_universe") == "-"
    assert summarize_ladder.cell(fallback, "word_universe") == "n/t"
    assert summarize_ladder.cell(fallback, "max_element_support") == "n/t"
    assert summarize_ladder.cell(fallback, "basis_size") == "-"  # still just absent
    assert summarize_ladder.cell(tracked, "word_universe") == "12"


def test_summarizer_rejects_a_foreign_schema(tmp_path):
    record = tmp_path / "foreign.jsonl"
    record.write_text(json.dumps({"model": "tfim", "method": "exact"}) + "\n")
    with pytest.raises(SystemExit, match="not an A-CASE ladder record"):
        summarize_ladder.load(record)


def test_fixed_slice_spans_the_family_rather_than_taking_its_head():
    family = list(range(40))
    assert run_acase_ladder.fixed_slice(family, 8, "prefix") == list(range(8))
    assert run_acase_ladder.fixed_slice(family, 8, "stride") == [0, 5, 10, 15,
                                                                20, 25, 30, 35]
    # a family smaller than the request is returned whole, not padded or empty
    assert run_acase_ladder.fixed_slice([1, 2, 3], 8, "stride") == [1, 2, 3]
    assert run_acase_ladder.fixed_slice([], 8, "stride") == []
    assert run_acase_ladder.fixed_slice(family, 0, "stride") == []
    with pytest.raises(ValueError, match="unknown fixed-subspace selection"):
        run_acase_ladder.fixed_slice(family, 8, "middle")


def test_both_fixed_arms_choose_their_slice_and_record_it():
    """A fixed subspace is committed to before any measurement, so *which* slice
    it takes is part of the method. The committed record uses ``stride`` for QSE
    and for generator coordinates alike, because the natural prefix of either
    family is all singles -- Brillouin-dead on a Hartree-Fock reference, which
    block-diagonalizes the projected Hamiltonian and returns E_HF exactly. Both
    slices stay available and each row records which one it used.
    """
    from clifford_qc.backends import ExactMVBackend

    model = run_acase_ladder.build_system({"type": "tfim", "n": 4})
    context = {"rho": ExactMVBackend().state(model.reference, ()), "observables": {},
               "candidates": run_acase_ladder.build_candidates(model, 3),
               "pool": run_acase_ladder.word_pool(model)}
    for method, family in (("generator_coordinate", "candidates"), ("qse", "pool")):
        spec = {"kind": method, "size": 4}
        assert len(context[family]) > 4  # otherwise the two slices coincide
        prefix = run_acase_ladder.run_method(method, spec | {"selection": "prefix"},
                                            model, context)
        stride = run_acase_ladder.run_method(method, spec | {"selection": "stride"},
                                            model, context)
        assert prefix["selection"] == "prefix" and stride["selection"] == "stride"
        assert prefix["labels"] != stride["labels"], method
        # stride is the default, so the committed config's choice is not a trap
        assert run_acase_ladder.run_method(method, spec, model,
                                          context)["labels"] == stride["labels"]
    with pytest.raises(ValueError, match="unknown fixed-subspace selection"):
        run_acase_ladder.run_method("qse", {"kind": "qse", "selection": "middle"},
                                    model, context)


def test_the_krylov_arm_has_no_slice_to_choose():
    """A Krylov sequence is H^k for consecutive k -- striding it would build a
    different, worse-conditioned space rather than a fairer sample of the same
    one. The row records ``selection: null`` so the column cannot be misread."""
    from clifford_qc.backends import ExactMVBackend

    model = run_acase_ladder.build_system({"type": "tfim", "n": 4})
    context = {"rho": ExactMVBackend().state(model.reference, ()), "observables": {},
               "candidates": (), "pool": ()}
    row = run_acase_ladder.run_method("krylov", {"kind": "krylov", "size": 3},
                                      model, context)
    assert row["selection"] is None


def test_unknown_systems_and_methods_are_rejected():
    with pytest.raises(ValueError, match="unknown system type"):
        run_acase_ladder.build_system({"type": "graphene"})
    model = run_acase_ladder.build_system({"type": "tfim", "n": 3})
    with pytest.raises(ValueError, match="unknown method kind"):
        run_acase_ladder.run_method("x", {"kind": "telepathy"}, model, {})
